channels:
- conda-forge
dependencies:
- python=3.13.9
- pip<=25.2
- pip:
  - mlflow==3.8.1
  - attrs==25.4.0
  - brotlicffi==1.0.9.2
  - cloudpickle==3.1.2
  - colorama==0.4.6
  - matplotlib==3.10.8
  - numpy==2.3.5
  - omegaconf==2.3.0
  - pydot==4.0.1
  - pytorch-lightning==2.6.0
  - rich==14.2.0
  - scipy==1.16.3
  - timm==1.0.22
  - zstandard==0.24.0
name: mlflow-env
