creation_timestamp: 1766813829629
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1766813829629
model_id: m-0ec9bdebe40a4e9387be244694dbf756
name: nsfw_detection_model
run_id: 06a8e44d7e5d41b6864bd10c803610f2
run_link: null
source: models:/m-0ec9bdebe40a4e9387be244694dbf756
status: READY
status_message: null
storage_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/models/m-0ec9bdebe40a4e9387be244694dbf756/artifacts
user_id: null
version: 5
