creation_timestamp: 1766813765011
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1766813765011
model_id: m-60a5bd9af071444d8e49f6aa9d584236
name: nsfw_detection_model
run_id: ead766ba0cc240afba5389c35e38ae97
run_link: null
source: models:/m-60a5bd9af071444d8e49f6aa9d584236
status: READY
status_message: null
storage_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/models/m-60a5bd9af071444d8e49f6aa9d584236/artifacts
user_id: null
version: 2
