artifact_uri: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/06a8e44d7e5d41b6864bd10c803610f2/artifacts
end_time: 1766813829689
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 06a8e44d7e5d41b6864bd10c803610f2
run_name: placid-wolf-412
source_name: ''
source_type: 4
source_version: ''
start_time: 1766813824434
status: 3
tags: []
user_id: temo4ka
