artifact_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0
creation_time: 1766797629154
experiment_id: '0'
last_update_time: 1766797629154
lifecycle_stage: active
name: Default
