artifact_uri: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/d56f12df85f94ba8aa514313c1f83e73/artifacts
end_time: 1766814024055
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d56f12df85f94ba8aa514313c1f83e73
run_name: magnificent-ox-638
source_name: ''
source_type: 4
source_version: ''
start_time: 1766814018148
status: 3
tags: []
user_id: temo4ka
