creation_timestamp: 1766813849939
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1766813849939
model_id: m-e33fe8835bd54c48bc5bcaa7f3c7b1d8
name: nsfw_detection_model
run_id: 5f1a7f023a7a4ebe93d52713ae255821
run_link: null
source: models:/m-e33fe8835bd54c48bc5bcaa7f3c7b1d8
status: READY
status_message: null
storage_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/models/m-e33fe8835bd54c48bc5bcaa7f3c7b1d8/artifacts
user_id: null
version: 6
