creation_timestamp: 1766814023996
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1766814023996
model_id: m-5f99a59b5c2e46d7a112449476b643a4
name: nsfw_detection_model
run_id: d56f12df85f94ba8aa514313c1f83e73
run_link: null
source: models:/m-5f99a59b5c2e46d7a112449476b643a4
status: READY
status_message: null
storage_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/models/m-5f99a59b5c2e46d7a112449476b643a4/artifacts
user_id: null
version: 7
