artifact_uri: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/236451232755784722/dc16c99d7bab4e2fb444b08bb9fa6cb3/artifacts
end_time: 1766809669872
entry_point_name: ''
experiment_id: '236451232755784722'
lifecycle_stage: active
run_id: dc16c99d7bab4e2fb444b08bb9fa6cb3
run_name: classy-rat-310
source_name: ''
source_type: 4
source_version: ''
start_time: 1766809054318
status: 3
tags: []
user_id: temo4ka
