creation_timestamp: 1766815360166
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1766815360166
model_id: m-c279bdb0bf17451392946e952c9dd873
name: nsfw_detection_model
run_id: c11c0f5cd24445368333ecfa13643d88
run_link: null
source: models:/m-c279bdb0bf17451392946e952c9dd873
status: READY
status_message: null
storage_location: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/models/m-c279bdb0bf17451392946e952c9dd873/artifacts
user_id: null
version: 9
