artifact_uri: file:///Users/temo4ka/StudyProjects/antiNSFW_validator/nsfw/.mlruns/0/5f1a7f023a7a4ebe93d52713ae255821/artifacts
end_time: 1766813849998
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5f1a7f023a7a4ebe93d52713ae255821
run_name: wistful-eel-801
source_name: ''
source_type: 4
source_version: ''
start_time: 1766813845600
status: 3
tags: []
user_id: temo4ka
